version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: safcftm
       MYSQL_DATABASE: brewlog
       MYSQL_USER: brewlog
       MYSQL_PASSWORD: brewlog

   app:
     depends_on:
       - db
     image: psaleh/brewlog-web
     volumes:
       - ./web-server-image/src:/var/www/html
     ports:
       - "8080:80"
     restart: always

   receiver:
     depends_on:
       - db
     image: psaleh/python-server
     ports:
       - "12345:12345"
     restart: always

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
      - 8081:80

volumes:
    db_data:
