version: '3'

services:
   db:
     image: mongo:latest
     volumes:
       - mongo_data:/data/db
     restart: always

   app:
     depends_on:
       - db
     image: node:latest
     volumes:
       - ./node-app/src:/node-app/src
     ports:
       - "8080:80"
     restart: always

   receiver:
     depends_on:
       - db
     image: psaleh/python-server-mongo
     volumes:
       - ./python-server/src:/run
     ports:
       - "12346:12346"

volumes:
    mongo_data:
